service: wealth-training-nexus-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x # Or nodejs16.x, nodejs20.x - choose a recent LTS
  region: us-east-1 # Change to your preferred AWS region
  environment:
    # Define environment variables for your Lambda function here
    # Example: Ensure these are set in your AWS Lambda console or through Serverless params
    # Database Configuration
    DB_USER: ${ssm:/wealthnexus/prod/db_user}
    DB_HOST: ${ssm:/wealthnexus/prod/db_host}
    DB_NAME: ${ssm:/wealthnexus/prod/db_name}
    DB_PASSWORD: ${ssm:/wealthnexus/prod/db_password~true} # ~true decrypts SecureString
    DB_PORT: ${ssm:/wealthnexus/prod/db_port}
    JWT_SECRET: ${ssm:/wealthnexus/prod/jwt_secret~true} # ~true decrypts SecureString
    GOOGLE_CLIENT_ID: ${ssm:/wealthnexus/prod/google_client_id}
    NODE_ENV: ${ssm:/wealthnexus/prod/node_env}
    CORS_ORIGIN: ${ssm:/wealthnexus/prod/cors_origin}

functions:
  api:
    handler: server/dist/lambda.handler # Updated path for compiled JS
    events:
      - httpApi: '*'
      # - http:
      #     path: '/{proxy+}'
      #     method: any
      #     cors: true

plugins:
  - serverless-offline # Useful for local testing, install with: npm install --save-dev serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - '!.*/**' # Exclude hidden files/folders like .git, .vscode etc.
    - '!.env'  # Exclude .env files
    - '!test/**'
    - '!src/**'      # Exclude frontend src
    - '!public/**'
    - '!serverless.yml'
    - '!README.md'
    - '!package.json' # Exclude root package.json
    - '!package-lock.json' # Exclude root package-lock.json
    - 'server/dist/**'         # Include all compiled JS from server/dist
    - 'server/node_modules/**' # Include server's node_modules
    # If you have other assets in server/dist (e.g., email templates), ensure they are included.

custom:
  serverless-offline:
    httpPort: 3001 # If you use serverless-offline
    lambdaPort: 3002
  dotenv:
    path: .env # or .env.production, .env.dev etc.
    include: # list of variables to load
      - DB_HOST
      - DB_USER
      # ... and so on for variables you want from the .env file 